name: hello-world
on:
  push:
    branches:
      - master  # Runs only when pushing to the master branch

jobs:
  my-job:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Runs on all 3 OS
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test example.spec.js --workers=1 --project=chromium --reporter=dot
